name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_WAVE_0C629C610 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "./Client" # App source code path
          api_location: "./Api" # Api source code path - optional
          output_location: "wwwroot" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
          production_branch: "main"
      - name: Send mailer
        # You may pin to the exact commit or the version.
        # uses: devellany/send-mail@45dbe31722b9c29635bc9d60315d420218093c56
        uses: devellany/send-mail@v1.0.2
        with:
          # Enter SMTP host.
          host: smtp.office365.com
          # Enter SMTP port. (defaults to 465)
          port: 587 
          # Enter SMTP host account.
          account: ${{ secrets.o365account }}
          # Enter SMTP host account password.
          password:  ${{ secrets.o365pwd }}
          # Enter sender name.
          sender:  ${{ secrets.o365sender }}
          # Enter sender mail.
          from: ${{ secrets.o365account }}
          # Enter recipient emails and separated with 'comma'. (The prefix 'file://' if you want to read a file)
          to: ${{ secrets.o365account }}
          # Enter the subject of the mail. (The prefix 'file://' if you want to read a file)
          subject: "email test"
          # Enter the body of the mail. (The prefix 'file://' if you want to read a file)
          body: "hello"
          # Enter Content-Type HTTP header. (defaults to 'text/plain')
          contentType: "text/plain"
          # Attachment files are entered as an array. Required key 'path'. (The prefix 'file://' if you want to read a file)


  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_WAVE_0C629C610 }}
          action: "close"


          
